# Generated by Django 6.0.6 on 2026-06-17 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'AI Usage Stat',
                'verbose_name_plural': 'AI Usage Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AiCoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tips', models.JSONField(help_text='The advice generated by the AI Coach or rule-based fallback.')),
                ('model_version', models.CharField(default='fallback', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('was_fallback', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Coaching Session',
                'verbose_name_plural': 'AI Coaching Sessions',
                'ordering': ['-generated_at'],
            },
        ),
    ]
