# Generated by Django 6.0.6 on 2026-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('registry', models.CharField(help_text="e.g. 'Verra', 'Gold Standard', 'Patch.io'", max_length=50)),
                ('price_per_tonne_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certification', models.CharField(help_text="e.g. 'VCS', 'GS', 'CCBS'", max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offset Project',
                'verbose_name_plural': 'Offset Projects',
                'ordering': ['price_per_tonne_usd'],
            },
        ),
    ]
