# Generated by Django 6.0.6 on 2026-06-17 06:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Primary identifier and login credential.', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Optional public name for leaderboard/challenges. Blank = anonymous.', max_length=60)),
                ('bio', models.TextField(blank=True, help_text='Optional short bio, 300 chars max.', max_length=300)),
                ('city', models.CharField(blank=True, help_text='Used for city-scoped leaderboard.', max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 country code. Used for national average comparison.', max_length=2)),
                ('privacy_level', models.CharField(choices=[('public', 'Public (name visible to all)'), ('friends', 'Friends only'), ('anonymous', 'Anonymous (no name shown)')], default='anonymous', help_text='Controls how name/data appears in social features. Default: anonymous.', max_length=20)),
                ('leaderboard_visible', models.BooleanField(default=False, help_text='Explicit opt-in for leaderboard participation. False by default.')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL (user-supplied or OAuth-provided).')),
                ('onboarding_complete', models.BooleanField(default=False, help_text='Whether the user has completed the onboarding calculator flow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out', models.BooleanField(default=False, help_text='Global opt-out. When True, no notifications sent regardless of other settings.')),
                ('opt_out_at', models.DateTimeField(blank=True, help_text='Timestamp when user opted out. Retained for compliance audit.', null=True)),
                ('email_enabled', models.BooleanField(default=True, help_text='Send notifications via email (requires Resend/SMTP config).')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Show in-app notification center badges.')),
                ('streak_reminders', models.BooleanField(default=True, help_text='Remind user when a streak is about to break.')),
                ('challenge_deadlines', models.BooleanField(default=True, help_text='Remind user of upcoming challenge deadlines.')),
                ('monthly_summary', models.BooleanField(default=True, help_text='Monthly footprint summary and progress report.')),
                ('new_challenges', models.BooleanField(default=False, help_text='Notify when new community challenges are published. Opt-in only.')),
                ('frequency_cap', models.CharField(choices=[('none', 'No cap (send as triggered)'), ('daily', 'At most once per day'), ('weekly', 'At most once per week'), ('monthly', 'At most once per month')], default='weekly', help_text='Maximum notification frequency regardless of trigger count.', max_length=10)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Timestamp of last sent notification. Used to enforce frequency_cap.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country'], name='idx_user_country'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['leaderboard_visible'], name='idx_user_leaderboard'),
        ),
    ]
