# Generated by Django 6.0.6 on 2026-06-17 06:25

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.CharField(db_index=True, help_text="Stable dot-notation identifier, e.g. 'transport.car.petrol.per_km'", max_length=200)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('energy', 'Energy'), ('diet', 'Diet & Food'), ('consumption', 'Consumption & Shopping'), ('waste', 'Waste & Recycling')], db_index=True, max_length=20)),
                ('subcategory', models.CharField(help_text="Human-readable subcategory, e.g. 'Petrol car (average)", max_length=100)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='Emission factor in the stated unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(help_text="e.g. 'kg_CO2e_per_km', 'kg_CO2e_per_kWh'", max_length=50)),
                ('source', models.CharField(help_text="Full citation, e.g. 'DEFRA/BEIS 2023 Conversion Factors for Company Reporting'", max_length=300)),
                ('source_url', models.URLField(help_text='Direct link to the source document or dataset')),
                ('source_version', models.CharField(help_text="Version string, e.g. '2023-v1'", max_length=50)),
                ('effective_date', models.DateField(help_text='Date from which this factor is considered current')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active factors are used in new calculations')),
                ('notes', models.TextField(blank=True, help_text='Additional context, assumptions, or regional applicability notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['category', 'factor_id', '-effective_date'],
                'indexes': [models.Index(fields=['factor_id', 'source_version'], name='idx_factor_id_version'), models.Index(fields=['category', 'is_active'], name='idx_factor_cat_active')],
            },
        ),
        migrations.CreateModel(
            name='FootprintEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date this footprint data represents (not necessarily today)')),
                ('mode', models.CharField(choices=[('quick', 'Quick Estimate'), ('detailed', 'Detailed Calculation')], default='quick', max_length=10)),
                ('total_co2e_kg', models.DecimalField(decimal_places=3, help_text='Total CO2-equivalent in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('factor_version', models.CharField(help_text="Emission factor source version used for this calculation, e.g. '2023-v1'", max_length=50)),
                ('raw_data', models.JSONField(help_text='Raw user inputs for audit/reproducibility. Not for display — use categories.')),
                ('period_days', models.PositiveSmallIntegerField(default=365, help_text='Number of days this entry represents (for partial-year handling)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprint_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Footprint Entry',
                'verbose_name_plural': 'Footprint Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FootprintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('energy', 'Energy'), ('diet', 'Diet & Food'), ('consumption', 'Consumption & Shopping'), ('waste', 'Waste & Recycling')], max_length=20)),
                ('co2e_kg', models.DecimalField(decimal_places=3, help_text='CO2-equivalent in kilograms for this category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total footprint', max_digits=5)),
                ('sub_breakdown', models.JSONField(blank=True, default=dict, help_text='Optional finer-grained breakdown within this category')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='calculator.footprintentry')),
            ],
            options={
                'verbose_name': 'Footprint Category',
                'verbose_name_plural': 'Footprint Categories',
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactorChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_factor_id', models.CharField(blank=True, max_length=200)),
                ('old_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('new_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source_citation', models.TextField(help_text='Source document and section justifying this change')),
                ('change_reason', models.TextField(help_text="Why was this factor changed? e.g. 'Annual DEFRA update to 2023 figures'")),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='Admin user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factor_changes', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changelog_entries', to='calculator.emissionfactor')),
            ],
            options={
                'verbose_name': 'Emission Factor Changelog',
                'verbose_name_plural': 'Emission Factor Changelog Entries',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['factor', '-changed_at'], name='idx_changelog_factor_date')],
            },
        ),
        migrations.AddIndex(
            model_name='footprintentry',
            index=models.Index(fields=['user', 'date'], name='idx_footprint_user_date'),
        ),
        migrations.AddIndex(
            model_name='footprintentry',
            index=models.Index(fields=['user', 'mode'], name='idx_footprint_user_mode'),
        ),
        migrations.AddIndex(
            model_name='footprintentry',
            index=models.Index(fields=['user', '-created_at'], name='idx_footprint_user_created'),
        ),
        migrations.AddIndex(
            model_name='footprintcategory',
            index=models.Index(fields=['entry', 'category'], name='idx_category_entry_cat'),
        ),
        migrations.AlterUniqueTogether(
            name='footprintcategory',
            unique_together={('entry', 'category')},
        ),
    ]
