# Generated by Django 6.0.6 on 2026-06-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalAverageDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('year', models.PositiveSmallIntegerField(db_index=True, help_text='The calendar year this data represents.')),
                ('per_capita_co2e_tonnes', models.DecimalField(decimal_places=3, help_text='Per capita emissions in metric tonnes CO2e.', max_digits=6)),
                ('source', models.CharField(default='Our World in Data (OWID)', max_length=200)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'National Average Dataset',
                'verbose_name_plural': 'National Average Datasets',
                'ordering': ['-year', 'country_code'],
                'unique_together': {('country_code', 'year')},
            },
        ),
    ]
