"""
Data models for the ai_coach app (Phase 7).

Stores session history, weekly cache tips, and token usage statistics for user coaching.
"""
from __future__ import annotations

from django.db import models
from django.conf import settings


class AiCoachingSession(models.Model):
    """Stores a generated weekly coaching tip session for a user."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="coaching_sessions",
        db_index=True,
    )
    generated_at = models.DateTimeField(auto_now_add=True, db_index=True)
    tips = models.JSONField(
        help_text="The advice generated by the AI Coach or rule-based fallback.",
    )
    model_version = models.CharField(max_length=100, default="fallback")
    tokens_used = models.PositiveIntegerField(default=0)
    was_fallback = models.BooleanField(default=False)

    class Meta:
        verbose_name = "AI Coaching Session"
        verbose_name_plural = "AI Coaching Sessions"
        ordering = ["-generated_at"]

    def __str__(self) -> str:
        source = "Fallback" if self.was_fallback else "AI"
        return f"{self.user} — {self.generated_at:%Y-%m-%d} ({source})"


class AiUsageStat(models.Model):
    """Tracks token and call usage metrics for budget checking."""

    date = models.DateField(unique=True, db_index=True)
    total_calls = models.PositiveIntegerField(default=0)
    total_tokens = models.PositiveIntegerField(default=0)
    total_cost_usd = models.DecimalField(max_digits=10, decimal_places=4, default=0.0000)

    class Meta:
        verbose_name = "AI Usage Stat"
        verbose_name_plural = "AI Usage Stats"
        ordering = ["-date"]

    def __str__(self) -> str:
        return f"{self.date}: {self.total_calls} calls, {self.total_tokens} tokens"
